name: Test and Release

on:
  push:
    branches:
      - main

jobs:
  tests:
    strategy:
      matrix:
        node:
          - "12"
          - "14"
          - "16"
          - "18"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install yarn dep
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Run type checking (Typescript)
        run: yarn tsc --noEmit
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install yarn dep
        run: yarn install
      - name: Check linting
        run: yarn lint
  version_match:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check version matching
        run: bin/check_version_change
  release:
    needs: [tests, lint, version_match]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install yarn dep
        run: yarn install
