name: Tests

on:
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        node:
          - "16"
          - "18"
          - "20"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - name: Install yarn dep
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Run type checking (Typescript)
        run: yarn tsc --noEmit
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Install yarn dep
        run: yarn install
      - name: Check linting
        run: yarn lint
